[rpm-ostree][kickstart] Move configuration
from the Kickstart file to the Containerfile.

diff --git a/kickstart/playtron-os_kickstart.cfg.template b/kickstart/playtron-os_kickstart.cfg.template
--- a/kickstart/playtron-os_kickstart.cfg.template
+++ b/kickstart/playtron-os_kickstart.cfg.template
@@ -18,6 +18,8 @@ fi
 ignoredisk --only-use=vda
 zerombr
 clearpart --all --initlabel --drives=vda
+# The only way to specify default kernel arguments with rpm-ostree is to specify them here in the Kickstart file.
+# https://github.com/ostreedev/ostree/issues/479#issuecomment-245266886
 bootloader --location=mbr --boot-drive=vda --append="mem_sleep_default=deep"
 autopart --type btrfs
 
@@ -43,19 +45,16 @@ timezone UTC --utc
 rootpw --lock
 
 # Enable the desktop environment.
-xconfig --defaultdesktop GNOME --startxonboot
+xconfig --startxonboot
 
-# Disable the Fedora first-time setup agent. We will (eventually) provide our own.
+# Disable the Fedora first-time user experience as Playtron has its own.
 firstboot --disable
 
 # Run post-installation shell commands.
 %post --logfile=/root/kickstart-post.log --erroronfail
 
-# Enable shell debug logging to show the commands that are run.
-set -x
-
-# Enable immediate exit on fail
-set -e
+# Enable (1) -e for immediate exit on fail and (2) -x for shell debug logging to show the commands that are run.
+set -e -x
 
 # Add registry token to the image to enable updates for private builds
 if [ -n "${REGISTRY_TOKEN}" ]; then
@@ -69,21 +68,5 @@ if [ -n "${REGISTRY_TOKEN}" ]; then
 	}' > /etc/ostree/auth.json
 fi
 
-# Create the "playtron" user manually.
-# https://bugzilla.redhat.com/show_bug.cgi?id=1838859
-# Put the user in the "wheel" group for elevated privileges and "input" for Autotest to work.
-grep -E '^input:' /usr/lib/group | tee -a /etc/group
-useradd -G wheel,input playtron
-echo "playtron:playtron" | chpasswd
-
-# Fix permissions.
-chown -R -v 1000:1000 /var/home/playtron
-
-# Hide the GRUB boot menu.
-crudini --ini-options=nospace --set /etc/default/grub "" GRUB_TIMEOUT 0
-crudini --ini-options=nospace --set /etc/default/grub "" GRUB_TIMEOUT_STYLE hidden
-
-# Rebuild the GRUB configuration file.
-# This will load hidden boot menu settings and the new EFI boot entries.
 grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
 %end
