[rpm-ostree][kickstart] Move configuration (#137)
from the Kickstart file to the Containerfile.

Not everything can be moved as Kickstart overrides some config files.

diff --git a/kickstart/playtron-os_kickstart.cfg.template b/kickstart/playtron-os_kickstart.cfg.template
--- a/kickstart/playtron-os_kickstart.cfg.template
+++ b/kickstart/playtron-os_kickstart.cfg.template
@@ -18,6 +18,8 @@ fi
 ignoredisk --only-use=vda
 zerombr
 clearpart --all --initlabel --drives=vda
+# The only way to specify default kernel arguments with rpm-ostree is to specify them here in the Kickstart file.
+# https://github.com/ostreedev/ostree/issues/479#issuecomment-245266886
 bootloader --location=mbr --boot-drive=vda --append="mem_sleep_default=deep"
 autopart --type btrfs
 
@@ -33,9 +35,6 @@ url --url="https://mirror.rackspace.com/fedora/releases/40/Everything/x86_64/os/
 keyboard --vckeymap=us --xlayouts='us'
 lang en_US.UTF-8
 
-# Enable SELinux (permissive mode).
-selinux --permissive
-
 # Default to UTC timezone.
 timezone UTC --utc
 
@@ -43,19 +42,13 @@ timezone UTC --utc
 rootpw --lock
 
 # Enable the desktop environment.
-xconfig --defaultdesktop GNOME --startxonboot
-
-# Disable the Fedora first-time setup agent. We will (eventually) provide our own.
-firstboot --disable
+xconfig --startxonboot
 
 # Run post-installation shell commands.
 %post --logfile=/root/kickstart-post.log --erroronfail
 
-# Enable shell debug logging to show the commands that are run.
-set -x
-
-# Enable immediate exit on fail
-set -e
+# Enable (1) -e for immediate exit on fail and (2) -x for shell debug logging to show the commands that are run.
+set -e -x
 
 # Add registry token to the image to enable updates for private builds
 if [ -n "${REGISTRY_TOKEN}" ]; then
@@ -75,9 +68,6 @@ fi
 grep -E '^input:' /usr/lib/group | tee -a /etc/group
 useradd -G wheel,input playtron
 echo "playtron:playtron" | chpasswd
-
-# Fix permissions.
-chown -R -v 1000:1000 /var/home/playtron
 
 # Hide the GRUB boot menu.
 crudini --ini-options=nospace --set /etc/default/grub "" GRUB_TIMEOUT 0
